config/routes.rb
require "monban/constraints/signed_in"
require "monban/constraints/signed_out"

Rails.application.routes.draw do
  resource :search, only: [:show]
  resources :landings, only: [:index]

  constraints Monban::Constraints::SignedIn.new do
    root "users#show", as: :profile
  end

  constraints Monban::Constraints::SignedOut.new do
    root "landings#show"
  end

  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :edit, :update, :show, :destroy]
end

app/models/user.rb
class User < ActiveRecord::Base
  has_attached_file :picture,
    default_url: "/images/missing.png"

  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\Z/
  validates :email, presence: true, uniqueness: true
  validates :password_digest, presence: true

  def full_name
    "#{first_name} #{last_name}"
  end

  def self.location_search(location_query)
    User.where("city ILIKE ?", "#{location_query}")
  end

  def self.name_search(last_name_query)
    User.where("last_name ILIKE ?", "#{last_name_query}")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Monban::ControllerHelpers
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :user_authorized?

  def user_authorized?
    @user == current_user
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    @user = current_user

    redirect_to user_path(@user)
  end
end

app/controllers/landings_controller.rb
class LandingsController < ApplicationController
  def show
  end

  def index
    render :show
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def show
    @location_results = User.location_search(params[:location_query])
    @name_results = User.name_search(params[:last_name_query])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
  end

  def create
    user = authenticate_session(session_params)

    if sign_in(user)
      redirect_to user_path(user)
    else
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = sign_up(user_params)

    if @user.valid?
      sign_in(@user)
      redirect_to edit_user_path(@user)
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if user_authorized?
      @user.update(user_params)
    end

    redirect_to user_path(@user)
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    if user_authorized?
      @user.destroy
    end

    redirect_to :root
  end

  private

  def user_params
    params.require(:user).permit(
      :city,
      :email,
      :first_name,
      :last_name,
      :password,
      :phone,
      :picture,
      :street_address,
      :state,
      :zip
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/landings/show.html.erb
<section class="container">
  <h1 class="title-ha">Find a Doctor You Trust</h1>
    <%= form_tag search_path, method: :get, class: "no-info" do %>
      <%= label_tag(:location_query, "Location", class: "label") %>
      <%= search_field_tag :location_query,
        params[:location_query],
        placeholder: "Search by Location",
        class: "label" %>
      <%= label_tag(:last_name_query, "Last Name", class: "label") %>
      <%= search_field_tag :last_name_query,
        params[:last_name_query],
        placeholder: "Search by Doctor's Last Name",
        class: "label" %>
      <%= submit_tag "Find Me A Doctor", class: "search" %>
    <% end %>
  </form>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Headr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <h1 class="title">
      <%= link_to "Psychologist Today", landings_path %>
    </h1>

  <% if signed_in? %>
    <div class="sign-out">
    <%= link_to "Profile", user_path(current_user), class: 'button' %>
    <%= link_to "Sign out", session_path, method: :delete, class: 'button secondary' %>
    </div>
  <% else %>
    <div class="sign-out">
    <%= link_to "Sign in", new_session_path, class: 'button sign-in' %>
    <%= link_to "Doctor, Sign up", new_user_path , class: 'button' %>
    </div>
  <% end %>
  </header>

<%= yield %>
  <main class="container">
  </main>
</body>
</html>

app/views/pages/home.html.erb
<section class="container">
  <h1 class="title-ha">Find a Doctor You Trust</h1>
  <form class="no-info">
    <h1 class="label">Location</h1>
    <input type="text" name:"location">
    <button class="search">Find Me A Doctor</button>
  </form>
</section>

app/views/pages/profile.html.erb
<h1>Profile</h1>

app/views/searches/show.html.erb
<section class="container">
<% if @location_results.present? %>
  <h1 class="profile">Search Results for <%= params[:location_query] %></h1>
  <%= render @location_results %>
<% elsif params[:location_query] != "" %>
  <p>Sorry, there are no registered psychologists in your city.</p>
<% end %>

<% if @name_results.present? %>
  <h1 class="profile">Search Results for <%= params[:last_name_query] %></h1>
  <%= render @name_results %>
<% elsif params[:last_name_query] != "" %>
  <p>Sorry, there are no registered psychologists by that name.</p>
<% end %>
</section>

app/views/users/_user.html.erb
<div class="results group">

  <%= link_to image_tag user.picture.url, class:"photo photo-list"%>

<%= link_to user.full_name, user_path(user), class:"list" %>

 <%= link_to "View Doctor", user_path(user), class: 'view button' %>

</div>

app/views/users/edit.html.erb
<%= form_for @user do |form| %>

  <% if @user.errors.any? %>
    <%= pluralize(@user.errors.count, "error") %> prevented your account from being created:
    <ul>
      <% @user.errors.full_messages.each do |error_message| %>
        <li><%= error_message %></li>
      <% end %>
    </ul>
  <% end %>

<section class="container">
  <div class="welcome profile">Welcome
    <%= link_to " Dr. #{current_user.last_name}", user_path(current_user) %>,
    please edit your profile below.
  </div>
  <div>
    <p class="photo"><%= image_tag @user.picture.url %>
    <%= form.file_field :picture %>
  </div>
  <div class="info">
  <div>
    <%= form.label :first_name, class: 'label'%>
    <%= form.text_field :first_name %>
  </div>
  <div>
    <%= form.label :last_name, class: 'label' %>
    <%= form.text_field :last_name %>
  </div>
  <div>
    <%= form.label :email, class: 'label'%>
    <%= form.email_field :email %>
  </div>
  <div>
    <%= form.label :street_address, class: 'label' %>
    <%= form.text_field :street_address %>
  </div>
  <div>
    <%= form.label :city, class: 'label' %>
    <%= form.text_field :city %>
  </div>
  <div>
    <%= form.label :state, class: 'label' %>
    <%= form.text_field :state %>
  </div>
  <div>
    <%= form.label :zip, class: 'label' %>
    <%= form.text_field :zip %>
  </div>
  <div>
    <%= form.label :phone, class: 'label' %>
    <%= form.text_field :phone %>
  </div>
  <div>
    <%= form.submit "Save Profile", class: 'save'%>
  </div>
</section>
<% end %>

app/views/users/new.html.erb
<%= form_for @user, html: { class: "no-info" } do |form| %>

  <% if @user.errors.any? %>
  <div class="error">
    <%= pluralize(@user.errors.count, "error") %> prevented your account from being created:
    <ul>
      <% @user.errors.full_messages.each do |error_message| %>
        <li><%= error_message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <section class="container">
    <div>
      <%= form.label :first_name %>
      <%= form.text_field :first_name %>
    </div>
    <div>
      <%= form.label :last_name %>
      <%= form.text_field :last_name %>
    </div>
    <div>
      <%= form.label :email %>
      <%= form.email_field :email %>
    </div>
    <div>
      <%= form.label :password %>
      <%= form.password_field :password %>
    </div>
    <div>
      <%= form.submit "Doctor, Sign up" %>
    </div>
  </section>
<% end %>

app/views/users/show.html.erb
<section class="container">
  <h1 class="profile">Doctor <%= (@user.last_name)%>'s Profile</h1>
  <div class="photo">
    <p class="label">Photo: <%= image_tag @user.picture.url,
      class: 'picture' %></p>
  </div>
  <div class="info">
    <ul>
      <li>Name<p>Doctor <%= @user.full_name %></p></li>
      <li>Email<p><%= @user.email %></p></li>
      <li>Address<p><%= @user.street_address %></br>
        <%= @user.city %>,
        <%= @user.state %>
        <%= @user.zip %></p></li>
      <li>Phone Number<p><%= @user.phone %></p></li>
    </ul>
    <% if user_authorized? %>
      <div class="edit button">
        <%= link_to "Edit Profile", edit_user_path(@user) %>
      </div>
      <div class="line">
        <%= button_to "Delete Account",
          user_path(@user),
          method: :delete,
          data: { confirm: "Are you sure want to delete your account?" },
          id: 'delete' %>
      </div>
    <% else %>
      <div class="edit button">
        <%= link_to "Schedule An Appointment", new_appointment_path %>
      </div>
    <% end %>
  </div>
</section>